# Generated by Django 3.0.8 on 2020-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=30, verbose_name='Слово')),
                ('transfer', models.CharField(db_index=True, max_length=30, verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['word'],
            },
        ),
    ]
