# Generated by Django 3.0.8 on 2020-08-04 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Слово')),
                ('transfer', models.CharField(db_index=True, max_length=30, verbose_name='Перевод')),
                ('users', models.ManyToManyField(related_name='words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
